{
 "title": "Hbase Hot storage",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Total QPS ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bench_db_operation{operation=\"tps\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "TPS - Payment create with new card ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bench_db_operation{operation=\"transaction_existing_card\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "TPS- Payment create with existing card ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(bench_db_operation{operation=\"transaction_existing_card\"}[1m]))/60"
    }
   ]
  },
  {
   "title": "p99- payments write new card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"transaction_new_card\"}[1m])) by (le, operation))",
     "legendFormat": "p99-payments write new card"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_with_new_card\"}[1m])) by (le, operation))",
     "legendFormat": "p9999-payments write new card"
    }
   ]
  },
  {
   "title": "p99 - payments write existing card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"transaction_existing_card\"}[1m])) by (le, operation))",
     "legendFormat": "p99-payments write existing card"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_with_existing_card\"}[1m])) by (le, operation))",
     "legendFormat": "p9999-payments write existing card"
    }
   ]
  },
  {
   "title": "DB - payment write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"payment_create\"}[1m])) by (le, operation))",
     "legendFormat": "p99-payment write"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_write\"}[1m])) by (le, operation))",
     "legendFormat": "p9999-payment write"
    }
   ]
  },
  {
   "title": "DB - Card write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"card_write\"}[1m])) by (le, operation))",
     "legendFormat": "p99-Card write"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_card_write\"}[1m])) by (le, operation))",
     "legendFormat": "p9999-Card write"
    }
   ]
  },
  {
   "title": "DB - Card Index fetch hit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"card_fetch_found\"}[1m])) by (le, operation))",
     "legendFormat": "p99-Card index write"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_card_fetch_found\"}[1m])) by (le, operation))",
     "legendFormat": "p99-Card index write"
    }
   ]
  },
  {
   "title": "DB - Card Index fetch miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bench_db_duration_histogram_bucket{operation=\"card_fetch_not_found\"}[1m])) by (le, operation))",
     "legendFormat": "p99-Card index write"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(bench_db_duration_histogram_bucket{operation=\"poc_payment_card_fetch_not_found\"}[1m])) by (le, operation))",
     "legendFormat": "p99-Card index write"
    }
   ]
  }
 ]
}